/*
Review Quiz Maker
Display/Driver class: sets up GUI and functions of each button, etc; implements the main method
Allows user to generate random quizzes based in each subject. User can add different subjects and questions for quizzes and review and can change the settings/format for each new quiz. Stores the current subject and quiz and keeps a list of subjects to be added to. 
 */

import java.util.*;
import javax.swing.JOptionPane;


public class Display extends javax.swing.JFrame {
    //default positions for panels
    private static int defX = 10, defY = 60, width = 580, height = 280;
    //list of all subjects
    private static List<Subject> subjects = new ArrayList<Subject>(Arrays.asList(new Subject("Math"), new Subject("Science"), new Subject("Social Studies"), new Subject("English")));
    //current subject
    private Subject sub = subjects.get(0);
    //does the user want to hide known questions
    private boolean hideKnown;
    //currect quiz
    private Quiz curQuiz = null;
    private static javax.swing.JLabel[] qLabels;
    private static javax.swing.JTextField[] txtAns;

    
    /**
     * Creates new form Main
     */
    public Display() {
        
        initComponents();
        setLayout(null);
        
        //set locations (display + panels)
        setLocationRelativeTo(null);
        pnlHome.setLocation(0, defY);
        pnlAddQ.setLocation(defX, defY);
        pnlQuizDisplay.setLocation(defX, defY);
        pnlReview.setLocation(defX, defY);
        pnlSetRev.setLocation(defX, defY);
        
        //set size of display + panels
        setSize(600, 375);
        pnlHome.setSize(590, height);
        pnlAddQ.setSize(width, height);
        pnlQuizDisplay.setSize(width, height);
        pnlReview.setSize(width, height);
        pnlSetRev.setSize(width, height);

        //make everything not in use not visible
        pnlAddQ.setVisible(false);
        pnlQuizDisplay.setVisible(false);
        pnlReview.setVisible(false);
        pnlSetRev.setVisible(false);
        
        //adds default subjects into combo box
        for (Subject s : subjects){
            cboSub.addItem(s.toString());
        }
        cboSub.addItem("New Subject");
                
        qLabels = new javax.swing.JLabel[] {lblQ1, lblQ2, lblQ3, lblQ4, lblQ5, lblQ6, lblQ7, lblQ8, lblQ9, lblQ10};
        txtAns = new javax.swing.JTextField[]{txtAns1, txtAns2, txtAns3, txtAns4, txtAns5, txtAns6, txtAns7, txtAns8, txtAns9, txtAns10};
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        pnlHome = new javax.swing.JPanel();
        Close = new javax.swing.JButton();
        btnAddQ = new javax.swing.JButton();
        btnNewQuiz = new javax.swing.JButton();
        btnRev = new javax.swing.JButton();
        pnlQuizOp = new javax.swing.JPanel();
        chkHideKnown = new javax.swing.JCheckBox();
        spnNumQ = new javax.swing.JSpinner();
        pnlAddQ = new javax.swing.JPanel();
        lblQ = new javax.swing.JLabel();
        lblAns = new javax.swing.JLabel();
        txtAddQ = new javax.swing.JTextField();
        txtAddAns = new javax.swing.JTextField();
        btnEnterQ = new javax.swing.JButton();
        btnCancelQ = new javax.swing.JButton();
        pnlQuizDisplay = new javax.swing.JPanel();
        sclQuiz = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblQ1 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        txtAns1 = new javax.swing.JTextField();
        txtAns2 = new javax.swing.JTextField();
        txtAns3 = new javax.swing.JTextField();
        txtAns4 = new javax.swing.JTextField();
        lblQ5 = new javax.swing.JLabel();
        txtAns5 = new javax.swing.JTextField();
        lblQ6 = new javax.swing.JLabel();
        lblQ7 = new javax.swing.JLabel();
        lblQ8 = new javax.swing.JLabel();
        lblQ9 = new javax.swing.JLabel();
        lblQ10 = new javax.swing.JLabel();
        txtAns6 = new javax.swing.JTextField();
        txtAns7 = new javax.swing.JTextField();
        txtAns9 = new javax.swing.JTextField();
        txtAns8 = new javax.swing.JTextField();
        txtAns10 = new javax.swing.JTextField();
        lblQuestions = new javax.swing.JLabel();
        lblAnswers = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnSeeCorrect = new javax.swing.JButton();
        btnExitQuiz = new javax.swing.JButton();
        pnlSetRev = new javax.swing.JPanel();
        cboQuizzes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRevQuiz = new javax.swing.JButton();
        btnRevAns = new javax.swing.JButton();
        btnCloseRecOptions = new javax.swing.JButton();
        lblLastScore = new javax.swing.JLabel();
        pnlReview = new javax.swing.JPanel();
        sclRev = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lblReview = new javax.swing.JLabel();
        btnCloseRev = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblSub = new javax.swing.JLabel();
        cboSub = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Review");

        pnlHome.setPreferredSize(new java.awt.Dimension(360, 174));

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        btnAddQ.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnAddQ.setText("Add a Question to Bank");
        btnAddQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQActionPerformed(evt);
            }
        });

        btnNewQuiz.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnNewQuiz.setText("Generate New Quiz");
        btnNewQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewQuizActionPerformed(evt);
            }
        });

        btnRev.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRev.setText("Review Previous Quizzes/Questions");
        btnRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevActionPerformed(evt);
            }
        });

        pnlQuizOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Quiz Options:"));

        chkHideKnown.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        chkHideKnown.setText("Hide questions I know");
        chkHideKnown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chkHideKnown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHideKnownActionPerformed(evt);
            }
        });

        spnNumQ.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        spnNumQ.setModel(new javax.swing.SpinnerNumberModel(10, 0, 10, 1));
        spnNumQ.setToolTipText("<html> Number of questions in new quiz </html>");

        javax.swing.GroupLayout pnlQuizOpLayout = new javax.swing.GroupLayout(pnlQuizOp);
        pnlQuizOp.setLayout(pnlQuizOpLayout);
        pnlQuizOpLayout.setHorizontalGroup(
            pnlQuizOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuizOpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkHideKnown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnNumQ, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlQuizOpLayout.setVerticalGroup(
            pnlQuizOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizOpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlQuizOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHideKnown)
                    .addComponent(spnNumQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(Close)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAddQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNewQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRev))
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(pnlQuizOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149))))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewQuiz)
                .addGap(18, 18, 18)
                .addComponent(pnlQuizOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddQ)
                .addGap(18, 18, 18)
                .addComponent(btnRev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Close)
                .addContainerGap())
        );

        pnlAddQ.setPreferredSize(new java.awt.Dimension(380, 140));

        lblQ.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ.setText("Question: ");

        lblAns.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblAns.setText("Answer:");

        txtAddQ.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAddQ.setText(" ");

        txtAddAns.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        btnEnterQ.setText("Add Question");
        btnEnterQ.setPreferredSize(new java.awt.Dimension(180, 29));
        btnEnterQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterQActionPerformed(evt);
            }
        });

        btnCancelQ.setText("Cancel");
        btnCancelQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddQLayout = new javax.swing.GroupLayout(pnlAddQ);
        pnlAddQ.setLayout(pnlAddQLayout);
        pnlAddQLayout.setHorizontalGroup(
            pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddQLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddQLayout.createSequentialGroup()
                        .addGroup(pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ)
                            .addComponent(lblAns))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddQ)
                            .addComponent(txtAddAns)))
                    .addGroup(pnlAddQLayout.createSequentialGroup()
                        .addComponent(btnCancelQ, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnterQ, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAddQLayout.setVerticalGroup(
            pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddQLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ)
                    .addComponent(txtAddQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAns)
                    .addComponent(txtAddAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelQ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sclQuiz.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sclQuiz.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblQ1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ1.setText("Question 1");

        lblQ2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ2.setText("Question 2");

        lblQ3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ3.setText("Question 3");

        lblQ4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ4.setText("Question 4");

        txtAns1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtAns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAns1ActionPerformed(evt);
            }
        });

        txtAns2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        txtAns3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        txtAns4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        lblQ5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ5.setText("Question 5");

        txtAns5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        lblQ6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ6.setText("Question 6");

        lblQ7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ7.setText("Question 7");

        lblQ8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ8.setText("Question 8");

        lblQ9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ9.setText("Question 9");

        lblQ10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblQ10.setText("Question 10");

        txtAns6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        txtAns7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        txtAns9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        txtAns8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        txtAns10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        lblQuestions.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblQuestions.setText("Questions:");

        lblAnswers.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblAnswers.setText("Answers:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ5, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ9, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ8, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ7, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ6, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAnswers)
                                            .addComponent(txtAns1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAns3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAns2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtAns10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAns9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtAns8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAns7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtAns6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAns5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAns4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuestions)
                    .addComponent(lblAnswers))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAns10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        sclQuiz.setViewportView(jPanel2);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnSeeCorrect.setText("See Correct Answers");
        btnSeeCorrect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeCorrectActionPerformed(evt);
            }
        });

        btnExitQuiz.setText("Close Quiz");
        btnExitQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuizDisplayLayout = new javax.swing.GroupLayout(pnlQuizDisplay);
        pnlQuizDisplay.setLayout(pnlQuizDisplayLayout);
        pnlQuizDisplayLayout.setHorizontalGroup(
            pnlQuizDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExitQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeeCorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap())
            .addComponent(sclQuiz)
        );
        pnlQuizDisplayLayout.setVerticalGroup(
            pnlQuizDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuizDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sclQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlQuizDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExitQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlQuizDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSeeCorrect)
                        .addComponent(btnSubmit)))
                .addContainerGap())
        );

        cboQuizzes.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cboQuizzes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Questions" }));
        cboQuizzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboQuizzesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("What do you want to review? ");

        btnRevQuiz.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRevQuiz.setText("Take Quiz");
        btnRevQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevQuizActionPerformed(evt);
            }
        });

        btnRevAns.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnRevAns.setText("Review Answers");
        btnRevAns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevAnsActionPerformed(evt);
            }
        });

        btnCloseRecOptions.setText("Back");
        btnCloseRecOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseRecOptionsActionPerformed(evt);
            }
        });

        lblLastScore.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblLastScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLastScore.setText("<html>Last Score: <br/>Highest Score: </html> ");
        lblLastScore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlSetRevLayout = new javax.swing.GroupLayout(pnlSetRev);
        pnlSetRev.setLayout(pnlSetRevLayout);
        pnlSetRevLayout.setHorizontalGroup(
            pnlSetRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetRevLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSetRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSetRevLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cboQuizzes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSetRevLayout.createSequentialGroup()
                        .addGroup(pnlSetRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCloseRecOptions)
                            .addGroup(pnlSetRevLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblLastScore, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlSetRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRevAns, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRevQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        pnlSetRevLayout.setVerticalGroup(
            pnlSetRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetRevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboQuizzes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSetRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlSetRevLayout.createSequentialGroup()
                        .addComponent(btnRevAns)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRevQuiz))
                    .addComponent(lblLastScore, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnCloseRecOptions)
                .addContainerGap())
        );

        sclRev.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        lblReview.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblReview.setText("Question 1");
        lblReview.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReview, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReview, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(223, 223, 223))
        );

        sclRev.setViewportView(jPanel3);

        btnCloseRev.setText("Back");
        btnCloseRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseRevActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReviewLayout = new javax.swing.GroupLayout(pnlReview);
        pnlReview.setLayout(pnlReviewLayout);
        pnlReviewLayout.setHorizontalGroup(
            pnlReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sclRev, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReviewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCloseRev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHome)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        pnlReviewLayout.setVerticalGroup(
            pnlReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sclRev, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseRev)
                    .addComponent(btnHome)))
        );

        lblSub.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblSub.setText("Subject:");

        cboSub.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cboSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlAddQ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                                .addComponent(pnlQuizDisplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlSetRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSub, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSub)
                    .addComponent(cboSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlAddQ, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlQuizDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(pnlSetRev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //sets what the current subject is when combo box selection is changed
    private void cboSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubActionPerformed
        if (cboSub.getSelectedItem().equals("New Subject")){
            //creates new subject if correlating combo box item is selected
            String name = JOptionPane.showInputDialog("Enter subject name: ", "Subject" + cboSub.getItemCount());
            if (name != null){
              Subject sub = new Subject(name);
              subjects.add(sub);
              cboSub.insertItemAt(sub.toString(), cboSub.getItemCount()-1);
              cboSub.setSelectedIndex(cboSub.getItemCount()-2);
            } 
        } else {
            //sets subject to user's selection
            sub = subjects.get(cboSub.getSelectedIndex());
        }
        cboQuizzes.setSelectedIndex(0);
        
        //default number of questions is 10 or number within subject (whichever is lower)
        if (sub.getNumQ() > 10){
            spnNumQ.setValue(10);
        } else {
            spnNumQ.setValue(sub.getNumQ());
        }

    }//GEN-LAST:event_cboSubActionPerformed

    //closes GUI
    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    //changes status of hideKnown
    private void chkHideKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHideKnownActionPerformed
        if (chkHideKnown.isSelected())
            hideKnown = true;
        else
            hideKnown = false;
    }//GEN-LAST:event_chkHideKnownActionPerformed

    private void txtAns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAns1ActionPerformed

    //submit quiz - checks answers, display's score
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //checks each question
        for (int i = 0; i < curQuiz.getNumQ(); i++) {
            curQuiz.checkQ(i, txtAns[i].getText());
            txtAns[i].setEditable(false);
        }
        
        btnSubmit.setEnabled(false);
        //allow user to review answers
        btnSeeCorrect.setEnabled(true);
        
        //display score
        JOptionPane.showMessageDialog(null, "Score: " + curQuiz.calcScore() + "%");
        
        //resets quiz score stored
        curQuiz.reset();
    }//GEN-LAST:event_btnSubmitActionPerformed

    //closes opened quiz, asks if user wants to save quiz (if not already saved)
    private void btnExitQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitQuizActionPerformed
        //asks to save quiz or not
        
        if(!curQuiz.isSaved()){
            String[] options = {"Save", "Don't Save"};
            int save = JOptionPane.showOptionDialog(null, "Do you want to save this quiz?", "Save Quiz", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
            //user enters title if presses save
            if (save == 0) {
                String title = JOptionPane.showInputDialog("Enter title: ", sub.toString() + (sub.getNumQuizzes() + 1));
                curQuiz.setTitle(title);
                sub.saveQuiz(curQuiz);
                cboQuizzes.addItem(title);
            }
        }
        
        //returns home
        close();
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnExitQuizActionPerformed

    //displays a saved quiz
    private void btnRevQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevQuizActionPerformed
        close();
        
        //if user selects all questions and there are more than 10, shows message (only 10 questions can be displayed)
        if(curQuiz.getAllQ().length > 10)
            JOptionPane.showMessageDialog(null, "Only showing 10 questions");
        
        btnSubmit.setEnabled(true);
        displayQuiz(curQuiz);
    }//GEN-LAST:event_btnRevQuizActionPerformed

    //opens answers
    private void btnSeeCorrectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeCorrectActionPerformed

        JOptionPane.showMessageDialog(null, "Correct answers in green; wrong answers in red");
        for (int i = 0; i < curQuiz.getNumQ(); i++){
            //adds answers
            qLabels[i].setText("<html>" + (i+1) + "." + curQuiz.getQuestion(i).toString() + "</html>");
        }
    }//GEN-LAST:event_btnSeeCorrectActionPerformed

    //shows quiz's questions and answers
    private void btnRevAnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevAnsActionPerformed
        lblReview.setText(curQuiz.toString());
        pnlSetRev.setVisible(false);
        JOptionPane.showMessageDialog(null, "Answers previously correct are in green and incorrect are in red");
        pnlReview.setVisible(true);
        cboSub.setEnabled(false);
        txtAddQ.setText("");
        txtAddAns.setText("");
    }//GEN-LAST:event_btnRevAnsActionPerformed

    //changes curent quiz to user's selection
    private void cboQuizzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboQuizzesActionPerformed
        int selected = cboQuizzes.getSelectedIndex();
        if (selected == 0) {
            //all questions
            curQuiz = sub.reviewAll(false);
            lblLastScore.setText("<html> Last Score:   &emsp;&emsp;&ensp;" + sub.getLast() + "%<br/> Highest Score: &emsp;" + sub.getHighest() + "%</html>");

        } else {
            //specific quiz
            curQuiz = sub.getQuiz(cboQuizzes.getSelectedIndex() - 1);
            lblLastScore.setText("<html> Last Score:   &emsp;&emsp;&ensp;" + curQuiz.getLast() + "%<br/> Highest Score: &emsp;" + curQuiz.getHighest() + "%</html>");
        }
    }//GEN-LAST:event_cboQuizzesActionPerformed

    //goes back to review settings
    private void btnCloseRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseRevActionPerformed
        close();
        pnlSetRev.setVisible(true);
    }//GEN-LAST:event_btnCloseRevActionPerformed

    //closes review settings and returns to home screen
    private void btnCloseRecOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseRecOptionsActionPerformed
        close();
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnCloseRecOptionsActionPerformed

    //returns to home screen
    private void btnCancelQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelQActionPerformed
        close();
        txtAddAns.setText("");
        txtAddQ.setText("");
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnCancelQActionPerformed

    //creates new question, adds it to the subject's question bank, returns to home screen
    private void btnEnterQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterQActionPerformed
        //retrieve question and answer from input
        String question = txtAddQ.getText(), answer = txtAddAns.getText();

        //error message is user does not input both question and answer
        if (question.equals("") || answer.equals("")){
            JOptionPane.showMessageDialog(null, "Enter a question and answer");
        } else {
            sub.addQuestion(question, answer);
            close();
            pnlHome.setVisible(true);
        }
        
        //reset text fields
        txtAddAns.setText("");
        txtAddQ.setText("");

    }//GEN-LAST:event_btnEnterQActionPerformed

    private void btnAddQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQActionPerformed
        close();
        pnlAddQ.setVisible(true);
    }//GEN-LAST:event_btnAddQActionPerformed

    private void btnNewQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewQuizActionPerformed
        //error if not enough questions to make up a quiz (<10)
        int numQ = (int)spnNumQ.getValue();
        btnSubmit.setEnabled(true);
        
        if (numQ > qLabels.length){
            //number of questions exceeded maximum
            JOptionPane.showMessageDialog(null, "<html> Select fewer questions (max. " + qLabels.length + ") </html>");  
        } else if (numQ == 0){
            //0 questions selected
            JOptionPane.showMessageDialog(null, "<html> Select more than 0 questions </html>");
        }else if(sub.getNumQ() < numQ || (hideKnown && sub.getNumQ() - sub.getNumKnown() < numQ)){
            //too few questions to generate preferred quiz
            JOptionPane.showMessageDialog(null, "<html> Not enough questions available to generate quiz </html>");
        }else {
            //confirms preferred quiz, generates it, and displays
            if (JOptionPane.showConfirmDialog(null, "New " + sub + " quiz with " + numQ + " questions?", "New Quiz", 0) == 0){
                close();
                curQuiz = sub.makeQuiz(numQ, hideKnown);
                displayQuiz(curQuiz);
            }
        }     
            
    }//GEN-LAST:event_btnNewQuizActionPerformed

    private void btnRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevActionPerformed
        //opens review panel
        close();
        cboQuizzes.setSelectedIndex(0);
        pnlSetRev.setVisible(true);
        lblLastScore.setText("<html> Last Score:   &emsp;&emsp;&ensp;" + sub.getLast() + "%<br/> Highest Score: &emsp;" + sub.getHighest() + "%</html>");
    }//GEN-LAST:event_btnRevActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        //returns to home panel
        close();
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    //displays quiz for user to take
    private void displayQuiz(Quiz quiz){
        
        //sets/displays each question, clears answer boxes
        for (int i = 0; i < quiz.getNumQ(); i++){
            qLabels[i].setText("<html><p>" + (i+1) + ". " + quiz.getQuestion(i).getQ() + "</p></html>");
            txtAns[i].setText("");
            txtAns[i].setEditable(true);
            qLabels[i].setVisible(true);
            txtAns[i].setVisible(true);
        }
        
        //sets excess questions as not viewable
        if (quiz.getNumQ() < qLabels.length){
            for (int i = quiz.getNumQ(); i < qLabels.length; i++){
                qLabels[i].setVisible(false);
                txtAns[i].setVisible(false);
            }
        }
        
        //displays the quiz
        pnlQuizDisplay.setVisible(true);
        btnSeeCorrect.setEnabled(false);
        cboSub.setEnabled(false);
    }
    
    //closes all panels
    private void close(){
        pnlHome.setVisible(false);
        pnlAddQ.setVisible(false);
        pnlQuizDisplay.setVisible(false);
        pnlReview.setVisible(false);
        pnlSetRev.setVisible(false);
        cboSub.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
        
        //sample/default questions - replace as needed
        subjects.get(0).addQuestion("What is the greatest common factor of 42, 126, and 210?", "42");
        subjects.get(0).addQuestion("What is the sum of (7 + 3i) + (−8 + 9i)?", "−1 + 12i");
        subjects.get(0).addQuestion("If a/b = 2, what is the value of 4b/a?", "2");
        subjects.get(0).addQuestion("For the function g(x)=ax^2+24, a is a constant and g(4) = 8. What is the value of g(−4)?", "8");
        subjects.get(0).addQuestion("If t > 0 and t^2−4=0, what is the value of t?", "2");
        subjects.get(0).addQuestion("If y(x-1)=z then x=", "z/y+1");
        subjects.get(0).addQuestion("Two angles of a triangle measure 15° and 85 °. What is the measure for the third angle?", "80");
        subjects.get(0).addQuestion("For every 6 molecules of carbon dioxide consumed, 1 molecule of glucose is produced. What defines the function f that gives the number of molecules, f(x), of glucose produced when x molecules of carbon dioxide are consumed?", "f(x)=x/6");
        subjects.get(0).addQuestion("What is the minimum value of f(x)=x^2-8x+4", "-12");
        subjects.get(0).addQuestion("What is the area of a right triangle with legs of 30 and 40 units in length", "600");
        
        subjects.get(1).addQuestion("What suffix is used on the second element in a two element compound?", "-ide");
        subjects.get(1).addQuestion("What is the name for the compound CO2?", "carbon dioxide");
        subjects.get(1).addQuestion("How would you write the chemical formula for the compound dinitrogen monoxide?", "N2O");
        subjects.get(1).addQuestion("What prefix is used if there are three atoms of an element in a given compound?", "tri-");
        subjects.get(1).addQuestion("If a compound is made from a metal element and a non-metal element, which element goes first in the name?", "metal element");
        subjects.get(1).addQuestion("What prefix is used if there are two atoms of an element in a given compound?", "di-");
        subjects.get(1).addQuestion("What is the name for the compound S3N2?", "trisulfur dinitride");
        subjects.get(1).addQuestion("What is the common name for the compound dihydrogen monoxide?", "water");
        subjects.get(1).addQuestion("What positively charged particle is located at the center of the atom in the nucleus?", "proton");
        subjects.get(1).addQuestion("What is a substance called that consists of a single type of atom?", "element");
        
        subjects.get(2).addQuestion("Who was the first European to land in North America?", "Leif Erikson");
        subjects.get(2).addQuestion("What was the name of the Pilgrims’ ship? ", "The Mayflower");
        subjects.get(2).addQuestion("What year was the Jamestown settlement established? ", "1607");
        subjects.get(2).addQuestion("What year were the first enslaved Africans brought to American colonies?", "1619");
        subjects.get(2).addQuestion("With the Proclamation Line of 1763, the British forbid American colonists from settling west of which natural barrier?", "The Appalachian Mountains");
        subjects.get(2).addQuestion("How do historians refer to the time period in the 1730s and 1740s when colonists began embracing secular rationalism over religion? ", "The First Great Awakening");
        subjects.get(2).addQuestion("What were colonists protesting with the Boston Tea Party?", "The Stamp Act");
        subjects.get(2).addQuestion("How many original British colonies existed in America?", "13");
        subjects.get(2).addQuestion("What was the first governing document of the newly created United States, later replaced by the U.S. Constitution?", "Articles of Confederation");
        subjects.get(2).addQuestion("What was Jefferson's election also known as?", "the Revolution of 1800");

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton btnAddQ;
    private javax.swing.JButton btnCancelQ;
    private javax.swing.JButton btnCloseRecOptions;
    private javax.swing.JButton btnCloseRev;
    private javax.swing.JButton btnEnterQ;
    private javax.swing.JButton btnExitQuiz;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNewQuiz;
    private javax.swing.JButton btnRev;
    private javax.swing.JButton btnRevAns;
    private javax.swing.JButton btnRevQuiz;
    private javax.swing.JButton btnSeeCorrect;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboQuizzes;
    private javax.swing.JComboBox<String> cboSub;
    private javax.swing.JCheckBox chkHideKnown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAns;
    private javax.swing.JLabel lblAnswers;
    private javax.swing.JLabel lblLastScore;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ10;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ6;
    private javax.swing.JLabel lblQ7;
    private javax.swing.JLabel lblQ8;
    private javax.swing.JLabel lblQ9;
    private javax.swing.JLabel lblQuestions;
    private javax.swing.JLabel lblReview;
    private javax.swing.JLabel lblSub;
    private javax.swing.JPanel pnlAddQ;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlQuizDisplay;
    private javax.swing.JPanel pnlQuizOp;
    private javax.swing.JPanel pnlReview;
    private javax.swing.JPanel pnlSetRev;
    private javax.swing.JScrollPane sclQuiz;
    private javax.swing.JScrollPane sclRev;
    private javax.swing.JSpinner spnNumQ;
    private javax.swing.JTextField txtAddAns;
    private javax.swing.JTextField txtAddQ;
    private javax.swing.JTextField txtAns1;
    private javax.swing.JTextField txtAns10;
    private javax.swing.JTextField txtAns2;
    private javax.swing.JTextField txtAns3;
    private javax.swing.JTextField txtAns4;
    private javax.swing.JTextField txtAns5;
    private javax.swing.JTextField txtAns6;
    private javax.swing.JTextField txtAns7;
    private javax.swing.JTextField txtAns8;
    private javax.swing.JTextField txtAns9;
    // End of variables declaration//GEN-END:variables
}
